full_name = input("Enter your Full Name: ")
age = int(input("Enter your Age: "))
city = input("Enter your City: ")
university = input("Enter your University: ")
department = input("Enter your Department: ")
favorite_language = input("Enter your Favorite programming language: ")
goal = input("Enter your Programming Goal: ")

print("===================================")
print("       STUDENT INTRODUCTION        ")
print("===================================\n")
print(f"My name is {full_name}.")
print(f"I am {age} years old.")
print(f"I live in {city}.")
print(f"I study {department} at {university}.")
print(f"My favorite programming language is {favorite_language}.\n")

print(f"My programming goal: ")
print(goal)
print()
print("=================================")