student_name = input("Enter your Full name: ")
student_id = input("Enter your Student_ID: ")
department = input("Enter your Department: ")
year = int(input("Enter your Academic year:  "))
university = input("Enter your University: ")
phone = input("Enter your phone number: ")

print("+-----------------------------------+")
print("|          Student ID Card          |")
print("+-----------------------------------+")
print(f"|Name: {student_name}              |")
print(f"|ID: {student_id}                  |")
print(f"|Department: {department}          |")
print(f"|Year: {year}                      |")
print(f"|University: {university}          |")
print(f"|Phone: {phone}                    |")
print("+-----------------------------------+")