name = input("Enter Full Name: ")
student_id= input("Enter Student ID: ")
age = int(input("Enter Age: "))
city = input("Enter City: ")
university = input("Enter University: ")
department = input("Enter Department: ")
email = input("Enter Email Address: ")
phone = int(input("Enter Phone Number: "))
favorite_language = input("Enter Favorite Programming Language: ")
programming_goal = input("Enter Programming Goal: ")

print("===================================================")
print("               AKIBA STUDENT PROFILE               ")
print("===================================================\n")

print(f"Name:                 {name}")
print(f"Student ID:           {student_id}")
print(f"Age:                  {age}")
print(f"City:                 {city}")
print(f"Department:           {department}")
print(f"Email:                {email}")
print(f"Phone:                {phone}")
print(f"Favorite Language:    {favorite_language}\n")

print(f"Programming Goal:")
print(programming_goal)
print()
print("===================================================")
